# Generated by Django 4.2.15 on 2024-08-29 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="blog", name="author",),
        migrations.DeleteModel(name="Gallery",),
        migrations.DeleteModel(name="GeneralInfo",),
        migrations.DeleteModel(name="HeroCarousel",),
        migrations.DeleteModel(name="UpcomingEvent",),
        migrations.DeleteModel(name="ViewMore",),
        migrations.DeleteModel(name="Author",),
        migrations.DeleteModel(name="Blog",),
    ]
