# Generated by Django 4.2.15 on 2024-08-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="viewmore",
            name="bg_image",
            field=models.ImageField(blank=True, null=True, upload_to="view_images/"),
        ),
    ]
